id: I25279783
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T00:05:36+00:00'
last_modified: '2022-06-07T12:10:16.025974+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ7445
  title: བཀའ་འགྱུར། ༼ལི་ཐང༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    ED4B:
      image_group_id: I1KG9868
      title: Volume 1 of bka' 'gyur/ (li thang /)
      total_pages: 632
      order: 1
      base_file: ED4B.txt
    A4A4:
      image_group_id: I1KG9869
      title: Volume 2 of bka' 'gyur/ (li thang /)
      total_pages: 642
      order: 2
      base_file: A4A4.txt
    '4283':
      image_group_id: I1KG9870
      title: Volume 3 of bka' 'gyur/ (li thang /)
      total_pages: 632
      order: 3
      base_file: 4283.txt
    BDF8:
      image_group_id: I1KG9871
      title: Volume 4 of bka' 'gyur/ (li thang /)
      total_pages: 1228
      order: 4
      base_file: BDF8.txt
    897B:
      image_group_id: I1KG9872
      title: Volume 5 of bka' 'gyur/ (li thang /)
      total_pages: 603
      order: 5
      base_file: 897B.txt
    1FF4:
      image_group_id: I1KG9873
      title: Volume 6 of bka' 'gyur/ (li thang /)
      total_pages: 569
      order: 6
      base_file: 1FF4.txt
    '4380':
      image_group_id: I1KG9874
      title: Volume 7 of bka' 'gyur/ (li thang /)
      total_pages: 600
      order: 7
      base_file: 4380.txt
    6E28:
      image_group_id: I1KG9875
      title: Volume 8 of bka' 'gyur/ (li thang /)
      total_pages: 530
      order: 8
      base_file: 6E28.txt
    5C03:
      image_group_id: I1KG9876
      title: Volume 9 of bka' 'gyur/ (li thang /)
      total_pages: 644
      order: 9
      base_file: 5C03.txt
    49A0:
      image_group_id: I1KG9877
      title: Volume 10 of bka' 'gyur/ (li thang /)
      total_pages: 662
      order: 10
      base_file: 49A0.txt
    EEE6:
      image_group_id: I1KG9878
      title: Volume 11 of bka' 'gyur/ (li thang /)
      total_pages: 666
      order: 11
      base_file: EEE6.txt
    003B:
      image_group_id: I1KG9879
      title: Volume 12 of bka' 'gyur/ (li thang /)
      total_pages: 596
      order: 12
      base_file: 003B.txt
    C219:
      image_group_id: I1KG9880
      title: Volume 13 of bka' 'gyur/ (li thang /)
      total_pages: 696
      order: 13
      base_file: C219.txt
    371F:
      image_group_id: I1KG9881
      title: Volume 14 of bka' 'gyur/ (li thang /)
      total_pages: 554
      order: 14
      base_file: 371F.txt
    '2957':
      image_group_id: I1KG9882
      title: Volume 15 of bka' 'gyur/ (li thang /)
      total_pages: 552
      order: 15
      base_file: 2957.txt
    BEFF:
      image_group_id: I1KG9883
      title: Volume 16 of bka' 'gyur/ (li thang /)
      total_pages: 560
      order: 16
      base_file: BEFF.txt
    62BD:
      image_group_id: I1KG9884
      title: Volume 17 of bka' 'gyur/ (li thang /)
      total_pages: 562
      order: 17
      base_file: 62BD.txt
    F189:
      image_group_id: I1KG9885
      title: Volume 18 of bka' 'gyur/ (li thang /)
      total_pages: 626
      order: 18
      base_file: F189.txt
    '2767':
      image_group_id: I1KG9886
      title: Volume 19 of bka' 'gyur/ (li thang /)
      total_pages: 598
      order: 19
      base_file: 2767.txt
    BA02:
      image_group_id: I1KG9887
      title: Volume 20 of bka' 'gyur/ (li thang /)
      total_pages: 602
      order: 20
      base_file: BA02.txt
    751A:
      image_group_id: I1KG9888
      title: Volume 21 of bka' 'gyur/ (li thang /)
      total_pages: 586
      order: 21
      base_file: 751A.txt
    F7E7:
      image_group_id: I1KG9889
      title: Volume 22 of bka' 'gyur/ (li thang /)
      total_pages: 654
      order: 22
      base_file: F7E7.txt
    FCC4:
      image_group_id: I1KG9890
      title: Volume 23 of bka' 'gyur/ (li thang /)
      total_pages: 584
      order: 23
      base_file: FCC4.txt
    '5625':
      image_group_id: I1KG9891
      title: Volume 24 of bka' 'gyur/ (li thang /)
      total_pages: 615
      order: 24
      base_file: 5625.txt
    9BD3:
      image_group_id: I1KG9892
      title: Volume 25 of bka' 'gyur/ (li thang /)
      total_pages: 636
      order: 25
      base_file: 9BD3.txt
    4A47:
      image_group_id: I1KG9893
      title: Volume 26 of bka' 'gyur/ (li thang /)
      total_pages: 632
      order: 26
      base_file: 4A47.txt
    C233:
      image_group_id: I1KG9894
      title: Volume 27 of bka' 'gyur/ (li thang /)
      total_pages: 616
      order: 27
      base_file: C233.txt
    5C65:
      image_group_id: I1KG9895
      title: Volume 28 of bka' 'gyur/ (li thang /)
      total_pages: 622
      order: 28
      base_file: 5C65.txt
    '8655':
      image_group_id: I1KG9896
      title: Volume 29 of bka' 'gyur/ (li thang /)
      total_pages: 624
      order: 29
      base_file: 8655.txt
    514A:
      image_group_id: I1KG9897
      title: Volume 30 of bka' 'gyur/ (li thang /)
      total_pages: 630
      order: 30
      base_file: 514A.txt
    E0B1:
      image_group_id: I1KG9898
      title: Volume 31 of bka' 'gyur/ (li thang /)
      total_pages: 642
      order: 31
      base_file: E0B1.txt
    5E9F:
      image_group_id: I1KG9899
      title: Volume 32 of bka' 'gyur/ (li thang /)
      total_pages: 608
      order: 32
      base_file: 5E9F.txt
    227D:
      image_group_id: I1KG9900
      title: Volume 33 of bka' 'gyur/ (li thang /)
      total_pages: 618
      order: 33
      base_file: 227D.txt
    B6F0:
      image_group_id: I1KG9901
      title: Volume 34 of bka' 'gyur/ (li thang /)
      total_pages: 572
      order: 34
      base_file: B6F0.txt
    4B7F:
      image_group_id: I1KG9902
      title: Volume 35 of bka' 'gyur/ (li thang /)
      total_pages: 588
      order: 35
      base_file: 4B7F.txt
    '4764':
      image_group_id: I1KG9903
      title: Volume 36 of bka' 'gyur/ (li thang /)
      total_pages: 628
      order: 36
      base_file: 4764.txt
    AB82:
      image_group_id: I1KG9904
      title: Volume 37 of bka' 'gyur/ (li thang /)
      total_pages: 593
      order: 37
      base_file: AB82.txt
    13D5:
      image_group_id: I1KG9905
      title: Volume 38 of bka' 'gyur/ (li thang /)
      total_pages: 544
      order: 38
      base_file: 13D5.txt
    '4438':
      image_group_id: I1KG9906
      title: Volume 39 of bka' 'gyur/ (li thang /)
      total_pages: 617
      order: 39
      base_file: 4438.txt
    C34B:
      image_group_id: I1KG9907
      title: Volume 40 of bka' 'gyur/ (li thang /)
      total_pages: 718
      order: 40
      base_file: C34B.txt
    F430:
      image_group_id: I1KG9908
      title: Volume 41 of bka' 'gyur/ (li thang /)
      total_pages: 624
      order: 41
      base_file: F430.txt
    88E1:
      image_group_id: I1KG9909
      title: Volume 42 of bka' 'gyur/ (li thang /)
      total_pages: 651
      order: 42
      base_file: 88E1.txt
    D637:
      image_group_id: I1KG9910
      title: Volume 43 of bka' 'gyur/ (li thang /)
      total_pages: 608
      order: 43
      base_file: D637.txt
    54B9:
      image_group_id: I1KG9911
      title: Volume 44 of bka' 'gyur/ (li thang /)
      total_pages: 628
      order: 44
      base_file: 54B9.txt
    A992:
      image_group_id: I1KG9912
      title: Volume 45 of bka' 'gyur/ (li thang /)
      total_pages: 628
      order: 45
      base_file: A992.txt
    6A9D:
      image_group_id: I1KG9913
      title: Volume 46 of bka' 'gyur/ (li thang /)
      total_pages: 634
      order: 46
      base_file: 6A9D.txt
    9AB5:
      image_group_id: I1KG9914
      title: Volume 47 of bka' 'gyur/ (li thang /)
      total_pages: 722
      order: 47
      base_file: 9AB5.txt
    31C0:
      image_group_id: I1KG9915
      title: Volume 48 of bka' 'gyur/ (li thang /)
      total_pages: 666
      order: 48
      base_file: 31C0.txt
    DABB:
      image_group_id: I1KG9916
      title: Volume 49 of bka' 'gyur/ (li thang /)
      total_pages: 568
      order: 49
      base_file: DABB.txt
    '8855':
      image_group_id: I1KG9917
      title: Volume 50 of bka' 'gyur/ (li thang /)
      total_pages: 666
      order: 50
      base_file: 8855.txt
    62BA:
      image_group_id: I1KG9918
      title: Volume 51 of bka' 'gyur/ (li thang /)
      total_pages: 644
      order: 51
      base_file: 62BA.txt
    F96F:
      image_group_id: I1KG9919
      title: Volume 52 of bka' 'gyur/ (li thang /)
      total_pages: 586
      order: 52
      base_file: F96F.txt
    A070:
      image_group_id: I1KG9920
      title: Volume 53 of bka' 'gyur/ (li thang /)
      total_pages: 722
      order: 53
      base_file: A070.txt
    09AF:
      image_group_id: I1KG9921
      title: Volume 54 of bka' 'gyur/ (li thang /)
      total_pages: 628
      order: 54
      base_file: 09AF.txt
    04DF:
      image_group_id: I1KG9922
      title: Volume 55 of bka' 'gyur/ (li thang /)
      total_pages: 652
      order: 55
      base_file: 04DF.txt
    86C8:
      image_group_id: I1KG9923
      title: Volume 56 of bka' 'gyur/ (li thang /)
      total_pages: 676
      order: 56
      base_file: 86C8.txt
    9FDD:
      image_group_id: I1KG9924
      title: Volume 57 of bka' 'gyur/ (li thang /)
      total_pages: 680
      order: 57
      base_file: 9FDD.txt
    BD60:
      image_group_id: I1KG9925
      title: Volume 58 of bka' 'gyur/ (li thang /)
      total_pages: 664
      order: 58
      base_file: BD60.txt
    F41A:
      image_group_id: I1KG9926
      title: Volume 59 of bka' 'gyur/ (li thang /)
      total_pages: 712
      order: 59
      base_file: F41A.txt
    DF7F:
      image_group_id: I1KG9927
      title: Volume 60 of bka' 'gyur/ (li thang /)
      total_pages: 674
      order: 60
      base_file: DF7F.txt
    C80E:
      image_group_id: I1KG9928
      title: Volume 61 of bka' 'gyur/ (li thang /)
      total_pages: 666
      order: 61
      base_file: C80E.txt
    4EE1:
      image_group_id: I1KG9929
      title: Volume 62 of bka' 'gyur/ (li thang /)
      total_pages: 688
      order: 62
      base_file: 4EE1.txt
    41A5:
      image_group_id: I1KG9930
      title: Volume 63 of bka' 'gyur/ (li thang /)
      total_pages: 666
      order: 63
      base_file: 41A5.txt
    '9213':
      image_group_id: I1KG9931
      title: Volume 64 of bka' 'gyur/ (li thang /)
      total_pages: 664
      order: 64
      base_file: 9213.txt
    41B7:
      image_group_id: I1KG9932
      title: Volume 65 of bka' 'gyur/ (li thang /)
      total_pages: 690
      order: 65
      base_file: 41B7.txt
    84B0:
      image_group_id: I1KG9933
      title: Volume 66 of bka' 'gyur/ (li thang /)
      total_pages: 676
      order: 66
      base_file: 84B0.txt
    '5983':
      image_group_id: I1KG9934
      title: Volume 67 of bka' 'gyur/ (li thang /)
      total_pages: 658
      order: 67
      base_file: 5983.txt
    84E4:
      image_group_id: I1KG9935
      title: Volume 68 of bka' 'gyur/ (li thang /)
      total_pages: 664
      order: 68
      base_file: 84E4.txt
    5A9D:
      image_group_id: I1KG9936
      title: Volume 69 of bka' 'gyur/ (li thang /)
      total_pages: 3
      order: 69
      base_file: 5A9D.txt
    1EA8:
      image_group_id: I1KG9937
      title: Volume 70 of bka' 'gyur/ (li thang /)
      total_pages: 648
      order: 70
      base_file: 1EA8.txt
    41E6:
      image_group_id: I1KG9938
      title: Volume 71 of bka' 'gyur/ (li thang /)
      total_pages: 596
      order: 71
      base_file: 41E6.txt
    8F4C:
      image_group_id: I1KG9939
      title: Volume 72 of bka' 'gyur/ (li thang /)
      total_pages: 3
      order: 72
      base_file: 8F4C.txt
    B767:
      image_group_id: I1KG9940
      title: Volume 73 of bka' 'gyur/ (li thang /)
      total_pages: 475
      order: 73
      base_file: B767.txt
    D4E6:
      image_group_id: I1KG9941
      title: Volume 74 of bka' 'gyur/ (li thang /)
      total_pages: 606
      order: 74
      base_file: D4E6.txt
    839B:
      image_group_id: I1KG9942
      title: Volume 75 of bka' 'gyur/ (li thang /)
      total_pages: 516
      order: 75
      base_file: 839B.txt
    B407:
      image_group_id: I1KG9943
      title: Volume 76 of bka' 'gyur/ (li thang /)
      total_pages: 594
      order: 76
      base_file: B407.txt
    1B0C:
      image_group_id: I1KG9944
      title: Volume 77 of bka' 'gyur/ (li thang /)
      total_pages: 564
      order: 77
      base_file: 1B0C.txt
    D3AC:
      image_group_id: I1KG9945
      title: Volume 78 of bka' 'gyur/ (li thang /)
      total_pages: 634
      order: 78
      base_file: D3AC.txt
    00F1:
      image_group_id: I1KG9946
      title: Volume 79 of bka' 'gyur/ (li thang /)
      total_pages: 682
      order: 79
      base_file: 00F1.txt
    3DAC:
      image_group_id: I1KG9947
      title: Volume 80 of bka' 'gyur/ (li thang /)
      total_pages: 716
      order: 80
      base_file: 3DAC.txt
    A4DE:
      image_group_id: I1KG9948
      title: Volume 81 of bka' 'gyur/ (li thang /)
      total_pages: 656
      order: 81
      base_file: A4DE.txt
    04C5:
      image_group_id: I1KG9949
      title: Volume 82 of bka' 'gyur/ (li thang /)
      total_pages: 704
      order: 82
      base_file: 04C5.txt
    84DE:
      image_group_id: I1KG9950
      title: Volume 83 of bka' 'gyur/ (li thang /)
      total_pages: 656
      order: 83
      base_file: 84DE.txt
    B266:
      image_group_id: I1KG9951
      title: Volume 84 of bka' 'gyur/ (li thang /)
      total_pages: 670
      order: 84
      base_file: B266.txt
    7F76:
      image_group_id: I1KG9952
      title: Volume 85 of bka' 'gyur/ (li thang /)
      total_pages: 710
      order: 85
      base_file: 7F76.txt
    48D8:
      image_group_id: I1KG9953
      title: Volume 86 of bka' 'gyur/ (li thang /)
      total_pages: 774
      order: 86
      base_file: 48D8.txt
    BECC:
      image_group_id: I1KG9954
      title: Volume 87 of bka' 'gyur/ (li thang /)
      total_pages: 656
      order: 87
      base_file: BECC.txt
    9BB6:
      image_group_id: I1KG9955
      title: Volume 88 of bka' 'gyur/ (li thang /)
      total_pages: 750
      order: 88
      base_file: 9BB6.txt
    49D2:
      image_group_id: I1KG9956
      title: Volume 89 of bka' 'gyur/ (li thang /)
      total_pages: 654
      order: 89
      base_file: 49D2.txt
    '3383':
      image_group_id: I1KG9957
      title: Volume 90 of bka' 'gyur/ (li thang /)
      total_pages: 506
      order: 90
      base_file: 3383.txt
    9C76:
      image_group_id: I1KG9958
      title: Volume 91 of bka' 'gyur/ (li thang /)
      total_pages: 3
      order: 91
      base_file: 9C76.txt
    9DC8:
      image_group_id: I1KG9959
      title: Volume 92 of bka' 'gyur/ (li thang /)
      total_pages: 670
      order: 92
      base_file: 9DC8.txt
    BA5D:
      image_group_id: I1KG9960
      title: Volume 93 of bka' 'gyur/ (li thang /)
      total_pages: 621
      order: 93
      base_file: BA5D.txt
    A53A:
      image_group_id: I1KG9961
      title: Volume 94 of bka' 'gyur/ (li thang /)
      total_pages: 614
      order: 94
      base_file: A53A.txt
    C2E4:
      image_group_id: I1KG9962
      title: Volume 95 of bka' 'gyur/ (li thang /)
      total_pages: 612
      order: 95
      base_file: C2E4.txt
    EC30:
      image_group_id: I1KG9963
      title: Volume 96 of bka' 'gyur/ (li thang /)
      total_pages: 602
      order: 96
      base_file: EC30.txt
    CAC1:
      image_group_id: I1KG9964
      title: Volume 97 of bka' 'gyur/ (li thang /)
      total_pages: 644
      order: 97
      base_file: CAC1.txt
    FAEC:
      image_group_id: I1KG9965
      title: Volume 98 of bka' 'gyur/ (li thang /)
      total_pages: 640
      order: 98
      base_file: FAEC.txt
    F513:
      image_group_id: I1KG9966
      title: Volume 99 of bka' 'gyur/ (li thang /)
      total_pages: 656
      order: 99
      base_file: F513.txt
    EE3B:
      image_group_id: I1KG9967
      title: Volume 100 of bka' 'gyur/ (li thang /)
      total_pages: 3
      order: 100
      base_file: EE3B.txt
    F81C:
      image_group_id: I1KG9968
      title: Volume 101 of bka' 'gyur/ (li thang /)
      total_pages: 690
      order: 101
      base_file: F81C.txt
    714D:
      image_group_id: I1KG9969
      title: Volume 102 of bka' 'gyur/ (li thang /)
      total_pages: 696
      order: 102
      base_file: 714D.txt
    31D2:
      image_group_id: I1KG9970
      title: Volume 103 of bka' 'gyur/ (li thang /)
      total_pages: 616
      order: 103
      base_file: 31D2.txt
    7E9A:
      image_group_id: I1KG9971
      title: Volume 104 of bka' 'gyur/ (li thang /)
      total_pages: 534
      order: 104
      base_file: 7E9A.txt
    12B1:
      image_group_id: I1KG9972
      title: Volume 105 of bka' 'gyur/ (li thang /)
      total_pages: 610
      order: 105
      base_file: 12B1.txt
    95E5:
      image_group_id: I1KG9973
      title: Volume 106 of bka' 'gyur/ (li thang /)
      total_pages: 554
      order: 106
      base_file: 95E5.txt
    E84D:
      image_group_id: I1KG9974
      title: Volume 107 of bka' 'gyur/ (li thang /)
      total_pages: 505
      order: 107
      base_file: E84D.txt
    CF88:
      image_group_id: I1KG9975
      title: Volume 108 of bka' 'gyur/ (li thang /)
      total_pages: 449
      order: 108
      base_file: CF88.txt
    C33A:
      image_group_id: I1KG9976
      title: Volume 109 of bka' 'gyur/ (li thang /)
      total_pages: 139
      order: 109
      base_file: C33A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
